const { test, expect } = require('@playwright/test');
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');

function listPs1Files(dir = ROOT, acc = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.name === 'node_modules' || entry.name === '.git') continue;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) listPs1Files(full, acc);
    else if (entry.name.endsWith('.ps1')) acc.push(full);
  }
  return acc;
}

function hasBom(buf) {
  return buf.length >= 3 && buf[0] === 0xef && buf[1] === 0xbb && buf[2] === 0xbf;
}

test('PowerShell scripts keep a UTF-8 BOM so Windows PowerShell 5.1 can parse them', () => {
  const files = listPs1Files();
  expect(files.length).toBeGreaterThan(0);
  const missing = files
    .filter((file) => !hasBom(fs.readFileSync(file)))
    .map((file) => path.relative(ROOT, file).replace(/\\/g, '/'));
  expect(missing).toEqual([]);
});

test('macOS/Linux pipeline scripts are Python, not Node or bash twins', () => {
  const scriptsDir = path.join(ROOT, 'scripts');
  const scripts = fs.readdirSync(scriptsDir);
  const requiredPy = [
    'download-gov.py',
    'parse-excel.py',
    'translate-questions.py',
    'convert-media.py',
    'filter-no-media.py',
    'merge-gov.py',
    'upload-media.py',
    'build-media-packs.py',
    'upload-packs.py',
  ];
  for (const name of requiredPy) {
    expect(scripts).toContain(name);
  }
  expect(scripts.filter((name) => name.endsWith('.sh'))).toEqual([]);
  expect(scripts.filter((name) => name.endsWith('.js'))).toEqual([]);

  const macos = fs.readFileSync(path.join(ROOT, 'Install_Prawko.macos.sh'), 'utf8');
  const linux = fs.readFileSync(path.join(ROOT, 'Install_Prawko.linux.sh'), 'utf8');
  const windows = fs.readFileSync(path.join(ROOT, 'Install_Prawko.windows.ps1'), 'utf8');
  for (const text of [macos, linux]) {
    expect(text).not.toMatch(/merge-gov\.js/);
    expect(text).not.toMatch(/download-gov\.sh/);
    expect(text).not.toMatch(/convert-media\.sh/);
    expect(text).toMatch(/run_pipeline download-gov\.py/);
    expect(text).toMatch(/merge-gov\.py/);
    expect(text).toMatch(/python3 "\$path"/);
  }
  expect(linux).not.toMatch(/node -p /);
  expect(windows).not.toMatch(/python3 /);
  expect(windows).not.toMatch(/merge-gov\.js/);
  expect(windows).toMatch(/merge-gov\.ps1/);
  expect(windows).not.toMatch(/function Merge-GovExcelIntoDataFiles/);
  expect(windows).toMatch(/&\s*robocopy\.exe/);
  expect(windows).not.toMatch(/Start-Process -FilePath "robocopy\.exe"/);
  expect(windows).toMatch(/Get-RobocopyCopyPlan/);
  expect(windows).toMatch(/ConvertTo-RobocopyDestFile/);
  expect(windows).toMatch(/OrigWriteTimeUtc/);
  expect(windows).toMatch(/Write-Progress -Activity \$activity -Status \$status/);
  expect(windows).not.toMatch(/counting files/);
  expect(windows).not.toMatch(/will copy \{0\} files/);
  expect(windows).not.toMatch(/already on destination, skipping/);
  expect(windows).toMatch(/\[switch\]\$Https/);
  expect(windows).toMatch(/httpsRedirect/);
  expect(linux).toMatch(/--https\|-Https\) HTTPS=1/);
  expect(macos).toMatch(/--https\|-Https\) HTTPS=1/);
  expect(fs.existsSync(path.join(ROOT, 'src', 'server.js'))).toBe(true);
  expect(windows).toMatch(/data\\translations_uk\.json/);
  expect(windows).toMatch(/Remove-Item -LiteralPath \$trUaDst -Force/);
  expect(macos).toMatch(/rm -f "\$dest_root\/src\/data\/translations_ua\.json"/);
  expect(linux).toMatch(/rm -f "\$dest_root\/src\/data\/translations_ua\.json"/);
  expect(scripts).toContain('merge-gov.ps1');
  expect(scripts).toContain('translate-questions.ps1');
  expect(scripts).toContain('translate-questions.skill.md');
});

test('ministry Excel and ZIPs live in server gov-cache; unpack is TEMP; scripts abort instead of spilling into the repo', () => {
  const downloadPs1 = fs.readFileSync(path.join(ROOT, 'scripts', 'download-gov.ps1'), 'utf8');
  expect(downloadPs1).not.toMatch(/Get-GovDataOverflowRoot/);
  expect(downloadPs1).not.toMatch(/Resolve-GovStagingDir/);
  expect(downloadPs1).toMatch(/function Assert-GovDiskSpace/);
  expect(downloadPs1).toMatch(/Join-Path \(Get-PrawkoServerRoot\) "gov-cache"/);
  expect(downloadPs1).toMatch(/function Expand-GovMediaZipsToTemp/);
  expect(downloadPs1).toMatch(/GetTempPath\(\)\) "prawko\\raw"/);
  const parsePs1 = fs.readFileSync(path.join(ROOT, 'scripts', 'parse-excel.ps1'), 'utf8');
  expect(parsePs1).toMatch(/Join-Path \(Get-GovDataDir\) "baza_pytan\.xlsx"/);
  expect(parsePs1).not.toMatch(/Join-Path \$repoRoot "gov-data\\baza_pytan\.xlsx"/);
  const downloadPy = fs.readFileSync(path.join(ROOT, 'scripts', 'download-gov.py'), 'utf8');
  expect(downloadPy).not.toMatch(/def overflow_root/);
  expect(downloadPy).toMatch(/def assert_disk_space/);
  expect(downloadPy).toMatch(/return server_root\(\) \/ "gov-cache"/);
  expect(downloadPy).toMatch(/def expand_gov_media_zips_to_temp/);
  const parsePy = fs.readFileSync(path.join(ROOT, 'scripts', 'parse-excel.py'), 'utf8');
  expect(parsePy).toMatch(/gov_data_dir\(\) \/ "baza_pytan\.xlsx"/);
  expect(parsePy).toMatch(/tr\["src"\] = "excel"/);
  expect(parsePy).toMatch(/kept\["src"\]/);
  expect(parsePy).not.toMatch(/default="gov-data\/baza_pytan\.xlsx"/);
  const windows = fs.readFileSync(path.join(ROOT, 'Install_Prawko.windows.ps1'), 'utf8');
  expect(windows).not.toMatch(/Get-GovDataOverflowRoot/);
  expect(windows).toMatch(/keeping gov-cache/);
  expect(windows).toMatch(/Join-Path \$targetDir "gov-cache"/);
  expect(windows).toMatch(/prawko\\gov-json/);
  const linux = fs.readFileSync(path.join(ROOT, 'Install_Prawko.linux.sh'), 'utf8');
  const macos = fs.readFileSync(path.join(ROOT, 'Install_Prawko.macos.sh'), 'utf8');
  expect(linux).toMatch(/TARGET_DIR\/gov-cache/);
  expect(macos).toMatch(/TARGET_DIR\/gov-cache/);
  expect(linux).not.toMatch(/\$GOV_DATA\/raw/);
  expect(macos).not.toMatch(/\$GOV_DATA\/raw/);
  expect(linux).toMatch(/prawko-gov-json/);
  expect(macos).toMatch(/prawko-gov-json/);
  expect(linux).toMatch(/--keep-raw/);
  expect(macos).toMatch(/--keep-raw/);
  const convertPy = fs.readFileSync(path.join(ROOT, 'scripts', 'convert-media.py'), 'utf8');
  expect(convertPy).toMatch(/--keep-raw/);
  expect(convertPy).toMatch(/dg\.remove_gov_raw_temp\(\)/);
  expect(fs.existsSync(path.join(ROOT, 'AGENTS.md'))).toBe(true);
  expect(fs.existsSync(path.join(ROOT, 'CODEX.md'))).toBe(false);
  const agentsMd = fs.readFileSync(path.join(ROOT, 'AGENTS.md'), 'utf8');
  expect(agentsMd).toMatch(/notes for AI agents/);
  expect(agentsMd).toMatch(/translate-questions\.skill\.md/);
  expect(agentsMd).not.toMatch(/\.cursor/);
  expect(agentsMd).not.toMatch(/Cursor/);
  const translatePs1 = fs.readFileSync(path.join(ROOT, 'scripts', 'translate-questions.ps1'), 'utf8');
  const translatePy = fs.readFileSync(path.join(ROOT, 'scripts', 'translate-questions.py'), 'utf8');
  expect(translatePs1).toMatch(/the same labels as the POLISH source/);
  expect(translatePs1).not.toMatch(/then q:\/a:\/b:\/c:/);
  expect(translatePs1).toMatch(/if \(-not \$script:TrSrc\.ContainsKey\(\$k\)\) \{ continue \}/);
  expect(translatePy).toMatch(/the same labels as the POLISH source/);
  expect(translatePy).not.toMatch(/then q:\/a:\/b:\/c:/);
  const deployYml = fs.readFileSync(path.join(ROOT, '.github', 'workflows', 'deploy.yml'), 'utf8');
  expect(deployYml).toMatch(/AGENTS\.md/);
  expect(deployYml).not.toMatch(/CODEX\.md/);
  const i18n = fs.readFileSync(path.join(ROOT, 'src', 'js', 'i18n.js'), 'utf8');
  expect(i18n).toMatch(/LANG_CYCLE = \['pl', 'en', 'de', 'uk'\]/);
  expect(i18n).toMatch(/translations_uk\.json/);
  const parsePs1Ua = fs.readFileSync(path.join(ROOT, 'scripts', 'parse-excel.ps1'), 'utf8');
  expect(parsePs1Ua).toMatch(/translations_uk\.json/);
  expect(parsePs1Ua).not.toMatch(/translations_ua\.json/);
  expect(parsePs1Ua).toMatch(/\$tr\['src'\] = 'excel'/);
  expect(parsePs1Ua).toMatch(/function Merge-ExistingQuestionTranslations/);
  expect(parsePs1Ua).toMatch(/SkipTranslateGaps/);
  expect(parsePs1Ua).toMatch(/Fill-MissingQuestionTranslations/);
  expect(translatePs1).toMatch(/LibraryOnly/);
  expect(translatePs1).toMatch(/if \(\$LibraryOnly\) \{ return \}/);
  expect(translatePs1).toMatch(/Write-Host \$msg -ForegroundColor Red/);
  expect(translatePs1).toMatch(/exit 1/);
  expect(translatePs1).toMatch(/function Fill-MissingQuestionTranslations/);
  expect(translatePs1).toMatch(/GeminiApiKey/);
  expect(translatePs1).toMatch(/Gemini failed; progress saved/);
  expect(translatePs1).not.toMatch(/Read-Host/);
  expect(translatePs1).toMatch(/v1beta\/models/);
  expect(translatePs1).not.toMatch(/googleapis\.com\/v1\/models/);
  expect(translatePs1).toMatch(/Write-Progress/);
  expect(translatePs1).toMatch(/function Write-TrProgress/);
  expect(translatePs1).not.toMatch(/Write-TrProgress \(\"Trying/);
  expect(translatePs1).toMatch(/WriteAllText\(\$tmp/);
  expect(translatePs1).toMatch(/preview\|experimental\|beta\|latest/);
  expect(translatePs1).toMatch(/function Get-GeminiFlashModelIds/);
  expect(translatePs1).toMatch(/function Test-TrGeminiFlashModel/);
  expect(translatePs1).toMatch(/pageSize=100/);
  expect(translatePs1).toMatch(/nextPageToken/);
  expect(translatePs1).not.toMatch(/Do not list \/v1beta\/models/);
  expect(translatePs1).toMatch(/Timeout = 30000/);
  expect(translatePs1).toMatch(/ReadWriteTimeout = 30000/);
  expect(translatePs1).toMatch(/timeout 30s/);
  expect(translatePs1).not.toMatch(/timeout 15s/);
  expect(translatePs1).toMatch(/timeout, trying next/);
  expect(translatePs1).not.toMatch(/timeout, skip question/);
  expect(translatePs1).toMatch(/function Set-QuestionSourceFields/);
  expect(translatePs1).toMatch(/\$script:TrSrc/);
  expect(translatePs1).not.toMatch(/function Get-QuestionFields/);
  expect(translatePs1).not.toMatch(/System\.Object\[\]/);
  expect(translatePs1).not.toMatch(/foreach \(\$item in @\(\$obj\)\)/);
  expect(translatePs1).not.toMatch(/Get-TrFieldValue \$item 'Field'/);
  expect(translatePs1).not.toMatch(/\$fields = @\(Get-QuestionFields/);
  expect(translatePs1).not.toMatch(/if \(\$script:TrSaved -and \$script:TrSaved.ContainsKey\('q'\)\) \{ return \}/);
  expect(translatePs1).not.toMatch(/Invoke-GeminiTranslateQuestion \$q/);
  expect(translatePs1).toMatch(/function Get-GeminiCandidateText/);
  expect(translatePs1).not.toMatch(/\$cands\.Count/);
  expect(translatePs1).toMatch(/bad response, trying next/);
  expect(translatePs1).toMatch(/function Test-TrField/);
  expect(translatePs1).toMatch(/function Get-TrLetterScript/);
  expect(translatePs1).toMatch(/function Get-TrMixedScriptWord/);
  expect(translatePs1).not.toMatch(/function Test-TrUkLatinLeftover/);
  expect(translatePs1).not.toMatch(/function Test-TrPolarityFlip/);
  expect(translatePs1).toMatch(/return 'mixed script'/);
  expect(translatePs1).toMatch(/TrCyrLangs/);
  expect(translatePs1).not.toMatch(/latin leftover/);
  expect(translatePs1).not.toMatch(/not Ukrainian/);
  expect(translatePs1).toMatch(/\\p\{L\}\{3,\}/);
  expect(translatePs1).not.toMatch(/\\p\{L\}\{4,\}/);
  expect(translatePs1).toMatch(/function Get-TrLen/);
  expect(translatePs1).toMatch(/function Get-TrGeminiTryOrder/);
  expect(translatePs1).toMatch(/function Add-TrModelName/);
  expect(translatePs1).toMatch(/unexpected model name format/);
  expect(translatePs1).not.toMatch(/list\.ToArray/);
  expect(translatePs1).toMatch(/finishReason=/);
  expect(translatePs1).toMatch(/\$script:TrLastMap/);
  expect(translatePs1).toMatch(/function Set-TrLastFields/);
  expect(translatePs1).toMatch(/\$script:TrLastQ/);
  expect(translatePs1).toMatch(/Dictionary\[string,string\]/);
  expect(translatePs1).toMatch(/\$script:TrSaved/);
  expect(translatePs1).not.toMatch(/saved \{0\}/);
  expect(translatePs1).toMatch(/\$script:TrLastBatch/);
  expect(translatePs1).toMatch(/function Add-TrGeminiDead/);
  expect(translatePs1).toMatch(/function Test-TrGeminiDailyQuota/);
  expect(translatePs1).toMatch(/function Get-TrRetryDelaySec/);
  expect(translatePs1).toMatch(/PerDay/);
  expect(translatePs1).toMatch(/daily quota, trying next/);
  expect(translatePs1).toMatch(/Gemini daily quota exhausted/);
  expect(translatePs1).toMatch(/Daily quota exhausted; re-run later/);
  expect(translatePs1).not.toMatch(/Start-Sleep -Seconds 19810/);
  expect(translatePs1).toMatch(/\$geminiBatchSize/);
  expect(translatePs1).toMatch(/Expect100Continue/);
  expect(translatePs1).toMatch(/KeepAlive = \$false/);
  expect(translatePs1).not.toMatch(/KeepAlive = \$true/);
  expect(translatePs1).toMatch(/connection closed, trying next/);
  expect(translatePs1).toMatch(/function Get-TrGeminiVersion/);
  expect(translatePs1).toMatch(/New-Object PSObject -Property/);
  expect(translatePs1).not.toMatch(/Write-Output -NoEnumerate/);
  expect(translatePs1).toMatch(/SkipVerifyAi/);
  expect(translatePs1).toMatch(/verify:/);
  expect(translatePs1).toMatch(/\{1\}, trying next/);
  expect(translatePs1).not.toMatch(/\{1\}, skip question/);
  expect(translatePs1).not.toMatch(/New-Object System\.Net\.WebClient/);
  expect(translatePs1).not.toMatch(/local\.json/);
  expect(translatePs1).toMatch(/x-goog-api-key/);
  expect(translatePs1).toMatch(/gemini-3\.5-flash-lite/);
  expect(translatePs1).toMatch(/"contents":\[\{"parts":/);
  expect(translatePs1).toMatch(/POLISH \{0\}:/);
  expect(translatePs1).toMatch(/translate-questions\.skill\.md/);
  expect(translatePs1).toMatch(/function Get-GeminiTranslateSkillTemplate/);
  expect(translatePs1).toMatch(/\.Replace\('\{lang\}'/);
  expect(translatePs1).toMatch(/uk = "Ukrainian"/);
  expect(translatePs1).toMatch(/\$existing\[\$qid\]\['src'\] = 'gemini'/);
  expect(translatePs1).toMatch(/@\('q', 'a', 'b', 'c', 'src'\)/);
  expect(translatePs1).not.toMatch(/Get-TranslationPath 'ua'/);
  expect(translatePs1).not.toMatch(/UK English/);
  expect(translatePs1).not.toMatch(/Translate Polish driving-licence theory exam questions into \$label/);
  expect(translatePs1).not.toMatch(/Do not copy the Polish source/);
  expect(translatePs1).not.toMatch(/Tak\/Nie in the source is exam text/);
  expect(translatePs1).not.toMatch(/Do not translate TAK\/NIE/);
  expect(translatePs1).not.toMatch(/UI chrome/);
  expect(translatePs1).not.toMatch(/Do not invent answers/);
  expect(translatePs1).not.toMatch(/Do not add extra options or explanations/);
  expect(translatePs1).toMatch(/function ConvertFrom-GeminiText/);
  expect(translatePs1).toMatch(/function Read-TrLabeledFields/);
  expect(translatePs1).toMatch(/function Get-TrTextBeforeLabels/);
  expect(translatePs1).toMatch(/function Read-TrParagraphFields/);
  expect(translatePs1).toMatch(/function Read-TrMarkdownFields/);
  expect(translatePs1).toMatch(/StartsWith\('\{'\) -or \$raw\.StartsWith\('\['\)/);
  expect(translatePs1).not.toMatch(/Return JSON only/);
  expect(translatePs1).not.toMatch(/Polish source JSON/);
  expect(translatePs1).not.toMatch(/responseMimeType/);
  expect(translatePs1).not.toMatch(/gemini-2\.0-flash/);
  expect(translatePy).toMatch(/gemini-api-key/);
  expect(translatePy).toMatch(/gemini_api_key/);
  expect(translatePy).toMatch(/Gemini failed; progress saved/);
  expect(translatePy).not.toMatch(/input\(/);
  expect(translatePy).toMatch(/load_gemini_model_ids/);
  expect(translatePy).toMatch(/GEMINI_MODELS_URL/);
  expect(translatePy).toMatch(/def is_text_flash_model/);
  expect(translatePy).toMatch(/pageSize/);
  expect(translatePy).toMatch(/nextPageToken/);
  expect(translatePy).not.toMatch(/Do not GET \/v1beta\/models/);
  expect(translatePy).toMatch(/v1beta\/models/);
  expect(translatePy).not.toMatch(/googleapis\.com\/v1\/models/);
  expect(translatePy).toMatch(/def write_progress/);
  expect(translatePy).toMatch(/print\(\"\\r\" \+ line/);
  expect(translatePy).toMatch(/tmp\.replace\(path\)/);
  expect(translatePy).not.toMatch(/trying \{model\} \(\{mi\}/);
  expect(translatePy).toMatch(/GEMINI_HTTP_TIMEOUT = 30/);
  expect(translatePy).toMatch(/_gemini_dead/);
  expect(translatePy).toMatch(/def gemini_daily_quota/);
  expect(translatePy).toMatch(/def gemini_retry_delay_sec/);
  expect(translatePy).toMatch(/PerDay/);
  expect(translatePy).toMatch(/daily quota, trying next/);
  expect(translatePy).toMatch(/Gemini daily quota exhausted/);
  expect(translatePy).toMatch(/Daily quota exhausted; re-run later/);
  expect(translatePy).toMatch(/gemini_translate_ids/);
  expect(translatePy).not.toMatch(/gemini_translate_question\(q, lang, gemini_api_key/);
  expect(translatePy).toMatch(/BATCH_SIZE/);
  expect(translatePy).toMatch(/timeout, trying next/);
  expect(translatePy).not.toMatch(/timeout, skip question/);
  expect(translatePy).toMatch(/connection closed, trying next/);
  expect(translatePy).toMatch(/def gemini_version_key/);
  expect(translatePy).toMatch(/def gemini_response_text/);
  expect(translatePy).toMatch(/def check_translation_field/);
  expect(translatePy).toMatch(/def _tr_letter_script/);
  expect(translatePy).toMatch(/def _tr_mixed_script_word/);
  expect(translatePy).not.toMatch(/def _tr_uk_latin_leftover/);
  expect(translatePy).not.toMatch(/def _tr_polarity_flip/);
  expect(translatePy).toMatch(/return "mixed script"/);
  expect(translatePy).toMatch(/_TR_CYR_LANGS/);
  expect(translatePy).not.toMatch(/latin leftover/);
  expect(translatePy).not.toMatch(/not Ukrainian/);
  expect(translatePy).toContain('[^\\W\\d_]{3,}');
  expect(translatePy).not.toContain('[^\\W\\d_]{4,}');
  expect(translatePy).toMatch(/def models_to_try/);
  expect(translatePy).toMatch(/def gemini_fail_hint/);
  expect(translatePy).toMatch(/skip-verify-ai/);
  expect(translatePy).toMatch(/verify:/);
  expect(translatePy).toMatch(/\{msg\}, trying next/);
  expect(translatePy).not.toMatch(/\{msg\}, skip question/);
  expect(translatePy).toMatch(/bad response, trying next/);
  expect(translatePy).toMatch(/preview.*experimental.*beta.*latest/);
  expect(translatePy).toMatch(/x-goog-api-key/);
  expect(translatePy).toMatch(/"contents": \[\{"parts":/);
  expect(translatePy).toMatch(/POLISH \{name\}:/);
  expect(translatePy).toMatch(/translate-questions\.skill\.md/);
  expect(translatePy).toMatch(/def load_translate_skill/);
  expect(translatePy).toMatch(/\.replace\("\{lang\}"/);
  expect(translatePy).toMatch(/"uk": "Ukrainian"/);
  expect(translatePy).toMatch(/dest\["src"\] = "gemini"/);
  expect(translatePy).not.toMatch(/legacy = root \/ "translations_ua.json"/);
  expect(translatePy).not.toMatch(/UK English/);
  expect(translatePy).not.toMatch(/Translate Polish driving-licence theory exam questions into \{label\}/);
  expect(translatePy).not.toMatch(/Do not copy the Polish source/);
  expect(translatePy).not.toMatch(/Tak\/Nie in the source is exam text/);
  expect(translatePy).not.toMatch(/Do not translate TAK\/NIE/);
  expect(translatePy).not.toMatch(/UI chrome/);
  expect(translatePy).not.toMatch(/Do not invent answers/);
  expect(translatePy).not.toMatch(/Do not add extra options or explanations/);
  expect(translatePy).toMatch(/def parse_labeled_fields/);
  expect(translatePy).toMatch(/def text_before_labels/);
  expect(translatePy).toMatch(/def parse_paragraph_fields/);
  expect(translatePy).toMatch(/def parse_markdown_fields/);
  expect(translatePy).toMatch(/startswith\("\{"\)/);
  expect(translatePy).toMatch(/def parse_gemini_reply/);
  expect(translatePy).not.toMatch(/Return JSON only/);
  expect(translatePy).not.toMatch(/Polish source JSON/);
  expect(translatePy).not.toMatch(/responseMimeType/);
  expect(translatePy).toMatch(/gemini-3\.5-flash-lite/);
  expect(translatePy).not.toMatch(/gemini-2\.0-flash/);
  expect(translatePy).toMatch(/resolve_gemini_api_key/);
  expect(translatePy).toMatch(/\.geminienv/);
  expect(translatePs1).toMatch(/function Resolve-GeminiApiKey/);
  expect(translatePs1).toMatch(/\.geminienv/);
  expect(fs.existsSync(path.join(ROOT, 'scripts', 'geminienv.example'))).toBe(true);
  expect(fs.readFileSync(path.join(ROOT, '.gitignore'), 'utf8')).toMatch(/^\.geminienv$/m);
  expect(fs.readFileSync(path.join(ROOT, 'scripts', 'geminienv.example'), 'utf8')).toMatch(/GEMINI_API_KEY=/);
  expect(parsePs1Ua).toMatch(/GeminiApiKey/);
  expect(parsePy).toMatch(/skip-translate-gaps/);
  expect(parsePy).toMatch(/fill_missing/);
  expect(parsePy).toMatch(/gemini-api-key/);
  expect(windows).toMatch(/SkipTranslateGaps/);
  expect(windows).toMatch(/-SkipTranslateGaps/);
  expect(windows).toMatch(/GeminiApiKey/);
  expect(windows).toMatch(/Gemini\s+only \(daily 429 tries the next Flash/);
  expect(windows).not.toMatch(/Google Translate fallback/);
  expect(windows).toMatch(/\$logParts\.Add\('\*\*\*'\)/);
  expect(linux).toMatch(/--skip-translate-gaps/);
  expect(linux).toMatch(/--gemini-api-key/);
  expect(linux).toMatch(/Gemini\s+only \(daily 429 tries the next Flash/);
  expect(linux).not.toMatch(/Google Translate fallback/);
  expect(macos).toMatch(/--skip-translate-gaps/);
  expect(macos).toMatch(/--gemini-api-key/);
  expect(macos).toMatch(/Gemini\s+only \(daily 429 tries the next Flash/);
  expect(macos).not.toMatch(/Google Translate fallback/);
});

test('HTTPS re-run fills only missing or invalid pieces', () => {
  const windows = fs.readFileSync(path.join(ROOT, 'Install_Prawko.windows.ps1'), 'utf8');
  const linux = fs.readFileSync(path.join(ROOT, 'Install_Prawko.linux.sh'), 'utf8');
  const macos = fs.readFileSync(path.join(ROOT, 'Install_Prawko.macos.sh'), 'utf8');
  expect(windows).toMatch(/function Sync-PrawkoGeneratedHttpsCerts/);
  expect(windows).toMatch(/function Get-PrawkoLocalCaCert/);
  expect(windows).toMatch(/function Test-PrawkoPemServerOk/);
  expect(windows).toMatch(/function Test-PrawkoCertDirAclOk/);
  expect(windows).toMatch(/CA ok \(private key, not expiring\)/);
  expect(windows).toMatch(/Server cert ok \(key, SAN, not expiring\)/);
  expect(windows).toMatch(/certs\\ ACL ok/);
  expect(windows).toMatch(/Service left running \(nothing to reconfigure\)/);
  expect(windows).toMatch(/httpsRedirect already true/);
  expect(windows).toMatch(/S-1-5-18/);
  expect(windows).toMatch(/return \$false/);
  expect(windows).not.toMatch(/function Install-PrawkoGeneratedHttpsCerts/);
  expect(windows).toMatch(/Re-run fills only gaps/);
  for (const text of [linux, macos]) {
    expect(text).toMatch(/https_cert_key_ok/);
    expect(text).toMatch(/https_tls_san_ok/);
    expect(text).toMatch(/Reusing existing Prawko Local CA/);
    expect(text).toMatch(/if \[ "\$tls_ok" -ne 1 \]/);
    expect(text).toMatch(/local\.json \$\{key\} already \$\{value\}/);
    expect(text).toMatch(/Service left running \(nothing to reconfigure\)/);
    expect(text).toMatch(/Re-run fills only gaps/);
  }
});
